# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/agent/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "v1/agent/service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16v1/agent/service.proto\x12\x08v1.agent"3\n\x0e\x43onnectRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t"6\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\t"(\n\x12\x45ventStreamRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t"&\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x32\x90\x01\n\x0c\x41gentService\x12?\n\x08Register\x12\x18.v1.agent.ConnectRequest\x1a\x19.v1.agent.ConnectResponse\x12?\n\x0cStreamEvents\x12\x1c.v1.agent.EventStreamRequest\x1a\x0f.v1.agent.Event0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.agent.service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONNECTREQUEST"]._serialized_start = 36
    _globals["_CONNECTREQUEST"]._serialized_end = 87
    _globals["_CONNECTRESPONSE"]._serialized_start = 89
    _globals["_CONNECTRESPONSE"]._serialized_end = 143
    _globals["_EVENTSTREAMREQUEST"]._serialized_start = 145
    _globals["_EVENTSTREAMREQUEST"]._serialized_end = 185
    _globals["_EVENT"]._serialized_start = 187
    _globals["_EVENT"]._serialized_end = 225
    _globals["_AGENTSERVICE"]._serialized_start = 228
    _globals["_AGENTSERVICE"]._serialized_end = 372
# @@protoc_insertion_point(module_scope)
